apiVersion: v1
kind: ConfigMap
metadata:
  name: featureflags-config-staging
  namespace: featureflags-staging
data:
  ENVIRONMENT: "staging"
  DEFAULT_FLAG_STRATEGY: "conservative"
  LOG_LEVEL: "INFO"
  API_PORT: "8001"
  DATABASE_URL: "sqlite:///./data/featureflags_staging.db"
