apiVersion: v1
kind: Service
metadata:
  name: featureflags-api-service
  namespace: featureflags-dev
  labels:
    app: featureflags-hub
    environment: dev
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: featureflags-hub
    environment: dev